name: Create ERP Image

on:
  push:
    tags: ["erp/v*"]

jobs:
  create-image:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '20'

      - name: Login to Docker Hub works
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build JAR with Maven
        run: |
          cd exchange-rate-provider
          mvn install